import { Router } from "express";
import { chatController } from "../controllers/chat.controller.js";
import { checkFirstMessage } from "../middlewares/checkChat.js";



export const chatRouter = Router();

// Route to get all the chats
chatRouter.get('/chats', chatController.getAll);

// Route to create a new chat with a title generated by AI and the first answer of AI
chatRouter.post('/chats', checkFirstMessage, chatController.createChat);

// Route to continue a chat already began 
chatRouter.post('/chats/:chatId/messages')
