import { Router } from "express";
import { chatController } from "../controllers/chat.controller.js";
import { checkChat } from "../middlewares/checkChat.js";
import { messageController } from "../controllers/message.controller.js";


export const chatRouter = Router();

// Route to get all the chats
chatRouter.get('/chats', chatController.getAll);

// Route to create a new chat with a title generated by IA
chatRouter.post('/chats', checkChat, chatController.createChat);
